language: ruby
rvm:
  - 2.3.1

services:
  - postgresql

before_script:
  - psql -c "create database seven_test;" -U postgres
  - psql -c "CREATE USER seven WITH PASSWORD 'seven';" -U postgres
  - psql -c "ALTER DATABASE seven_test OWNER TO seven;" -U postgres

script: bundle exec rake
