language: ruby
rvm:
  - 2.3.1

services:
  - postgresql

before_script:
  - psql -c 'create database seven_test;' -U postgres
  - psql -c "CREATE USER seven WITH PASSWORD 'seven';" -U postgres
script: bundle exec rake
