default: &default
  adapter: postgresql
  user: seven
  password: seven
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: seven_development

test:
  <<: *default
  database: seven_test

production:
  <<: *default
  database: seven_production
